### ISSUE TITLE
I like your program ! but add log.txt of the keys that i press 

### ISSUE THREAD

**Issue by Caiuzx** [KaustubhPatange/Kling#1]
Can add the possibility for log on txt up to down 
the keys that i press ? and visualize ?
with on/off on setting :D

**Comment by KaustubhPatange** [comment]
So you want a log feature which will create a log of buttons pressed in a txt file. Am i correct?

**Comment by Caiuzx** [comment]
yes ! thanks !

**Comment by Caiuzx** [comment]
thanks!

**Comment by KaustubhPatange** [comment]
Hey added your feature check latest release. It is already checked by default and will write log to app.log file in same directory of Kling.
