### ISSUE TITLE
REQUEST: Option to Choose Which Keys to show

### ISSUE THREAD

**Issue by lem98labs** [KaustubhPatange/Kling#12]
I can touch type but I often need to look at my laptop keyboard for some keys. It would be great to have the option of only showing keys from a list(e.g. Fkeys, ctrl,atl, fn)
Thanks

**Comment by KaustubhPatange** [comment]
Check the latest update. Also, side note the application cannot display <kbd>fn</kbd> key as there is no specific keycode present in [documentation](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.keys).
