### ISSUE TITLE
it does not show CTRL + ALT + SHIFT + ANY KEY together

### ISSUE THREAD

**Issue by thearslanstudio** [KaustubhPatange/Kling#3]
it does not show CTRL + ALT + SHIFT + ANY KEY together

**Comment by KaustubhPatange** [comment]
Right now four concurrent key bindings are not supported. I'll try to add the support through a hack since windows don't allow complex bindings capture!

**Comment by KaustubhPatange** [comment]
The issue has been fixed in the latest release. Check it out.
